# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67c51b59f841842a9a7a17afda7704fc92eaecfc8e42e5c1e3e45c7f29b42ae882bf4734e2c69d8e8a2455d69eaee5793268aeb4a6b46bd909c08e55bb7f4b0d

test:
  secret_key_base: 5a55bd1908c2ed4b79d4f6cd29a5e883329b500654bb448412658cb5ba70b86a89bc88ff48bb9a0ceaeeb1fb596913428043b6d67b703b691091925f0b3834e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
